### PR TITLE
Update twitter.cfg

### PR DESCRIPTION
**Pull request by jaydeeppatel1701**

### CODE REVIEW

**Comment by benjaminwalters** [comment]
This is a public repository. You should cancel this pull request and delete those credentials from your twitter account. Then you should generate new ones and upload them to your private GitHub repository. You should have gotten an email invitation to it.

**Comment by jaydeeppatel1701** [comment]
K

**Comment by shreeshbhat** [comment]
Why do we have write access to public repository in the first place?

**Comment by benjaminwalters** [comment]
We don't have write access. This is a pull request, which is asking the professor (or repository owner) to accept this code change. It would have to be approved before it were added to the repository.

**Comment by shreeshbhat** [comment]
Ah okay. Thanks for the explanation :)

**Comment by aronwc** [comment]
@jaydeeppatel1701 Also, you should probably just delete your fork of the main class repo (settings -> delete repository from your fork). Your twitter credentials still exist in the commit log.

@benjaminwalters thanks for your help!

**Pull request closed without merging**
